import type { ProviderGroup } from '@agentcowork/core-domain';
import type { ProviderCatalogEntry } from './types.js';

/**
 * User-facing group labels per spec §4a.6.
 * The spec says "internal taxonomy labels are NEVER shown to users" —
 * users see plain-English groupings: Free to start, Best value (PAYG), Frontier, etc.
 */
const GROUP_LABELS: Record<ProviderGroup, string> = {
  'forever-free': 'Free to start',
  aggregator: 'Multi-model access',
  payg: 'Best value (PAYG)',
  'eastern-frontier': 'Frontier',
  'western-frontier': 'Frontier',
  'self-hosted': 'Run your own model',
  'on-device': 'On-device',
  'web-search': 'Web search',
  'image-byok': 'Image generation',
  'video-byok': 'Video generation',
  mcp: 'Tools & data',
  services: 'Audio & TTS',
};

/** LLM chat BYOK tiles (Library → AI Providers). */
export const AI_PROVIDER_GROUPS: ProviderGroup[] = [
  'forever-free',
  'aggregator',
  'payg',
  'eastern-frontier',
  'western-frontier',
  'self-hosted',
];

/** Search, media, and MCP BYOK tiles (Library → Web & Other Providers). */
export const WEB_OTHER_PROVIDER_GROUPS: ProviderGroup[] = [
  'web-search',
  'image-byok',
  'video-byok',
  'mcp',
  'services',
];

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  // FOREVER FREE
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    group: 'forever-free',
    groupLabel: GROUP_LABELS['forever-free'],
    signupUrl: 'https://build.nvidia.com/',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'meta/llama-3.1-8b-instruct',
    description: 'Unlimited free inference with 80+ models. Strong default for BYOK.',
    recommended: true,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    group: 'forever-free',
    groupLabel: GROUP_LABELS['forever-free'],
    signupUrl: 'https://cloud.cerebras.ai/',
    baseUrl: 'https://api.cerebras.ai/v1',
    defaultModel: 'gpt-oss-120b',
    description: 'Very fast inference — production default gpt-oss-120b (free trial + PAYG).',
    recommended: true,
  },
  {
    id: 'google-ai-studio',
    name: 'Google AI Studio',
    group: 'forever-free',
    groupLabel: GROUP_LABELS['forever-free'],
    signupUrl: 'https://aistudio.google.com/apikey',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    defaultModel: 'gemini-2.0-flash',
    description: 'Gemini 2.5 Flash / 3 Flash with generous free quotas.',
    recommended: true,
  },

  // AGGREGATORS
  {
    id: 'openrouter',
    name: 'OpenRouter',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://openrouter.ai/',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'openrouter/free',
    description: 'Access 25+ free model slots with automatic failover.',
    recommended: false,
  },
  {
    id: 'opencode-go',
    name: 'OpenCode Go',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://opencode.ai/auth',
    baseUrl: 'https://opencode.ai/zen/go/v1',
    defaultModel: 'deepseek-chat',
    description: '$10/mo subscription to tested open coding models — GLM, Kimi, DeepSeek, MiMo, MiniMax, Qwen.',
    recommended: false,
  },
  {
    id: 'opencode-zen',
    name: 'OpenCode Zen',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://opencode.ai/auth',
    baseUrl: 'https://opencode.ai/zen/v1',
    defaultModel: 'nemotron-3-ultra-free',
    description: 'Curated coding models via OpenCode — PAYG. Free models available: Nemotron Ultra, DeepSeek.',
    recommended: false,
  },

  // WESTERN FRONTIER
  {
    id: 'openai',
    name: 'OpenAI',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://platform.openai.com/',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    description: 'GPT-4o mini (default) and GPT-4o frontier models.',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://console.anthropic.com/',
    baseUrl: 'https://api.anthropic.com/v1',
    defaultModel: 'claude-sonnet-5',
    description: 'Claude Sonnet 5 (default), Opus 4.8, Haiku 4.5, and Fable 5.',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://console.mistral.ai/',
    baseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'mistral-large-latest',
    description: 'Mistral Large and Pixtral multimodal models.',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://dashboard.cohere.com/',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    defaultModel: 'command-a',
    description: 'Command A and Command R+ optimized for RAG workflows.',
  },

  // PAYG FAST INFERENCE
  {
    id: 'groq',
    name: 'Groq',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://console.groq.com/',
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'openai/gpt-oss-120b',
    description: 'LPU inference — gpt-oss 120B/20B, Qwen, Groq Compound.',
  },
  {
    id: 'together',
    name: 'Together AI',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://api.together.ai/',
    baseUrl: 'https://api.together.xyz/v1',
    defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct-Turbo',
    description: 'Massive library of open-source models at low cost.',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://fireworks.ai/',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    description: 'High-performance inference platform.',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://deepinfra.com/',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    defaultModel: 'meta-llama/Meta-Llama-3.3-70B-Instruct',
    description: 'Low cost, scalable pay-as-you-go inference.',
  },

  // EASTERN FRONTIER
  {
    id: 'deepseek',
    name: 'DeepSeek',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://platform.deepseek.com/',
    baseUrl: 'https://api.deepseek.com/v1',
    defaultModel: 'deepseek-v4-flash',
    description:
      'DeepSeek V4 Flash (default) and V4 Pro via the official API. Legacy deepseek-chat/reasoner aliases retire 2026-07-24.',
  },
  {
    id: 'qwen',
    name: 'Qwen (Alibaba)',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://dashscope.aliyun.com/',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    defaultModel: 'qwen-plus',
    description: 'Alibaba Cloud Qwen family via DashScope (qwen-plus, qwen-max).',
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://open.bigmodel.cn/',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4/',
    defaultModel: 'glm-4-flash',
    description: 'GLM-4 Flash and GLM-4 Plus bilingual models.',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://siliconflow.cn/',
    baseUrl: 'https://api.siliconflow.com/v1',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    description: 'Access to DeepSeek V3, Qwen, and other Eastern models.',
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://platform.moonshot.cn/',
    baseUrl: 'https://api.moonshot.cn/v1',
    defaultModel: 'moonshot-v1-128k',
    description: 'Moonshot AI (Kimi) models. Use api.moonshot.ai for international.',
  },
  {
    id: 'kimi-code',
    name: 'Kimi Code',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://platform.moonshot.cn/',
    baseUrl: 'https://api.moonshot.cn/v1',
    defaultModel: 'kimi-k2-thinking',
    description: 'Kimi Code models optimized for coding tasks.',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://www.minimax.io/',
    baseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'MiniMax-Text-01',
    description: 'MiniMax AI models with long context support.',
  },
  {
    id: 'zai',
    name: 'Z.AI',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://z.ai/',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    defaultModel: 'glm-4.5',
    description: 'Z.AI GLM models via OpenAI/Anthropic-compatible APIs.',
  },
  {
    id: 'iflytek-spark',
    name: 'iFlytek Spark',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://xinghuo.xfyun.cn/',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    defaultModel: '4.0Ultra',
    description: 'iFlytek Spark (讯飞星火) models via OpenAI-compatible HTTP API.',
  },
  {
    id: 'iflytek-astron',
    name: 'iFlytek Astron MaaS',
    group: 'eastern-frontier',
    groupLabel: GROUP_LABELS['eastern-frontier'],
    signupUrl: 'https://www.xfyun.cn/',
    baseUrl: 'https://maas-api.cn-huabei-1.xf-yun.com/v1',
    defaultModel: 'xop3qwen1b7',
    description: 'iFlytek Astron MaaS (讯飞星辰) Token Plan / Coding Plan endpoints.',
  },

  // WESTERN / CLOUD FRONTIER (additional)
  {
    id: 'xai',
    name: 'xAI',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://console.x.ai/',
    baseUrl: 'https://api.x.ai/v1',
    defaultModel: 'grok-3',
    description: 'Grok models from xAI, including reasoning and multimodal.',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://portal.azure.com/',
    baseUrl: 'https://YOUR_RESOURCE.openai.azure.com/openai/v1',
    defaultModel: 'gpt-4o',
    description: 'Models through Azure OpenAI Service (API key). Set base URL to your resource.',
    // C.6: template endpoint can never be network-validated — key-only.
    validation: 'key-only',
  },
  {
    id: 'vertex-ai',
    name: 'GCP Vertex AI',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://console.cloud.google.com/vertex-ai',
    baseUrl: 'https://aiplatform.googleapis.com/v1',
    defaultModel: 'google/gemini-2.0-flash-001',
    description: 'Claude, Gemini and other models through Vertex AI (OpenAI-compatible proxy when configured).',
    validation: 'key-only',
  },
  {
    id: 'databricks',
    name: 'Databricks',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://www.databricks.com/',
    baseUrl: 'https://YOUR_WORKSPACE.cloud.databricks.com/serving-endpoints',
    defaultModel: 'databricks-meta-llama-3-3-70b-instruct',
    description: 'Models on Databricks Model Serving / AI Gateway (OpenAI-compatible).',
    validation: 'key-only',
  },
  {
    id: 'meta-api',
    name: 'Meta Model API',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://llama.developer.meta.com/',
    baseUrl: 'https://api.llama.com/compat/v1',
    defaultModel: 'Llama-4-Maverick-17B-128E-Instruct-FP8',
    description: "Meta's Model API — Llama family including Muse Spark models.",
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://www.perplexity.ai/settings/api',
    baseUrl: 'https://api.perplexity.ai',
    defaultModel: 'sonar',
    description: 'Chat models with built-in real-time web search grounding.',
  },
  {
    id: 'inception',
    name: 'Inception',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://www.inceptionlabs.ai/',
    baseUrl: 'https://api.inceptionlabs.ai/v1',
    defaultModel: 'mercury',
    description: 'Mercury models from Inception — diffusion-based fast inference.',
  },

  // PAYG / AGGREGATORS / GATEWAYS (additional)
  {
    id: 'huggingface',
    name: 'Hugging Face',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://huggingface.co/settings/tokens',
    baseUrl: 'https://router.huggingface.co/v1',
    defaultModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    description: 'Hugging Face Inference Providers via the Hugging Face Router.',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://novita.ai/',
    baseUrl: 'https://api.novita.ai/v3/openai',
    defaultModel: 'meta-llama/llama-3.1-8b-instruct',
    description: '90+ open-source models with OpenAI-compatible API.',
  },
  {
    id: 'avian',
    name: 'Avian',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://avian.io/',
    baseUrl: 'https://api.avian.io/v1',
    defaultModel: 'deepseek-chat',
    description: 'Cost-effective inference — DeepSeek, Kimi, GLM, MiniMax.',
  },
  {
    id: 'nanogpt',
    name: 'NanoGPT',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://nano-gpt.com/',
    baseUrl: 'https://nano-gpt.com/api/v1',
    defaultModel: 'chatgpt-4o-latest',
    description: 'Access multiple AI models through NanoGPT unified API.',
  },
  {
    id: 'litellm',
    name: 'LiteLLM',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://docs.litellm.ai/',
    baseUrl: 'http://127.0.0.1:4000/v1',
    defaultModel: 'gpt-4o-mini',
    description: 'LiteLLM proxy supporting many backends with prompt caching.',
  },
  {
    id: 'vercel-ai-gateway',
    name: 'Vercel AI Gateway',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://vercel.com/ai-gateway',
    baseUrl: 'https://ai-gateway.vercel.sh/v1',
    defaultModel: 'openai/gpt-4o-mini',
    description: 'Unified gateway to OpenAI, Anthropic, Google, xAI and more.',
  },
  {
    id: 'orcarouter',
    name: 'OrcaRouter',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://orcarouter.ai/',
    baseUrl: 'https://api.orcarouter.ai/v1',
    defaultModel: 'auto',
    description: 'Adaptive router for 150+ frontier models via one OpenAI API.',
  },
  {
    id: 'routstr',
    name: 'Routstr',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://routstr.com/',
    baseUrl: 'https://api.routstr.com/v1',
    defaultModel: 'gpt-4o-mini',
    description: 'OpenAI-compatible aggregator across dozens of upstream providers.',
  },
  {
    id: 'futurmix',
    name: 'FuturMix',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://futurmix.com/',
    baseUrl: 'https://api.futurmix.com/v1',
    defaultModel: 'gpt-4o-mini',
    description: 'Unified AI gateway (Anthropic, Google, OpenAI) OpenAI-compatible.',
  },
  {
    id: 'empiriolabs',
    name: 'EmpirioLabs AI',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://empiriolabs.com/',
    baseUrl: 'https://api.empiriolabs.com/v1',
    defaultModel: 'auto',
    description: 'Frontier open and proprietary chat models, OpenAI-compatible streaming.',
  },
  {
    id: 'venice',
    name: 'Venice.ai',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://venice.ai/',
    baseUrl: 'https://api.venice.ai/api/v1',
    defaultModel: 'llama-3.3-70b',
    description: 'Venice.ai models (Llama, DeepSeek, Mistral) with function calling.',
  },
  {
    id: 'scaleway',
    name: 'Scaleway',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://www.scaleway.com/en/generative-apis/',
    baseUrl: 'https://api.scaleway.ai/v1',
    defaultModel: 'llama-3.3-70b-instruct',
    description: 'European cloud generative APIs — open-source models.',
  },
  {
    id: 'ovhcloud',
    name: 'OVHcloud AI Endpoints',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://endpoints.ai.cloud.ovh.net/',
    baseUrl: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1',
    defaultModel: 'Meta-Llama-3_3-70B-Instruct',
    description: 'European OVHcloud AI-Endpoints open-source models.',
  },
  {
    id: 'saladcloud',
    name: 'SaladCloud AI Gateway',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://salad.com/',
    baseUrl: 'https://api.salad.com/api/public/v1',
    defaultModel: 'qwen2.5-7b',
    description: 'OpenAI-compatible access to SaladCloud-hosted Qwen and Gemma.',
  },
  {
    id: 'tensorix',
    name: 'Tensorix',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://tensorix.ai/',
    baseUrl: 'https://api.tensorix.ai/v1',
    defaultModel: 'qwen2.5-72b-instruct',
    description: '50+ open-source models with EU-hosted inference, zero data retention.',
  },
  {
    id: 'tetrate',
    name: 'Tetrate Agent Router',
    group: 'aggregator',
    groupLabel: GROUP_LABELS.aggregator,
    signupUrl: 'https://tetrate.io/',
    baseUrl: 'https://api.tetrate.io/v1',
    defaultModel: 'auto',
    description: 'Enterprise router for AI models (OpenAI-compatible).',
  },
  {
    id: 'near-ai',
    name: 'NEAR AI Cloud',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://near.ai/',
    baseUrl: 'https://cloud-api.near.ai/v1',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    description: 'TEE-backed private inference, OpenAI-compatible API.',
  },
  {
    id: 'snowflake',
    name: 'Snowflake Cortex',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://www.snowflake.com/en/data-cloud/cortex/',
    baseUrl: 'https://YOUR_ACCOUNT.snowflakecomputing.com/api/v2/cortex/inference:complete',
    defaultModel: 'llama3.1-70b',
    description: 'Latest models via Snowflake Cortex (set base URL to your account).',
    validation: 'key-only',
  },
  {
    id: 'sakana',
    name: 'Sakana AI',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://sakana.ai/',
    baseUrl: 'https://api.sakana.ai/v1',
    defaultModel: 'fugu',
    description: 'Sakana Fugu multi-agent system as one OpenAI-compatible model API.',
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    group: 'western-frontier',
    groupLabel: GROUP_LABELS['western-frontier'],
    signupUrl: 'https://aws.amazon.com/bedrock/',
    baseUrl: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    defaultModel: 'anthropic.claude-sonnet-4-20250514-v1:0',
    description:
      'Run models through Amazon Bedrock. Prefer an OpenAI-compatible Bedrock proxy URL + API key/bearer for mobile BYOK.',
    validation: 'key-only',
  },
  {
    id: 'sagemaker-tgi',
    name: 'Amazon SageMaker TGI',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://aws.amazon.com/sagemaker/',
    baseUrl: 'https://runtime.sagemaker.us-east-1.amazonaws.com/endpoints/YOUR_ENDPOINT/invocations',
    defaultModel: 'tgi',
    description: 'Text Generation Inference on SageMaker endpoints. Set base URL to your endpoint.',
    validation: 'key-only',
  },

  // SELF HOSTED / LOCAL
  {
    id: 'ollama',
    name: 'Ollama',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://ollama.com/',
    baseUrl: 'http://127.0.0.1:11434/v1',
    defaultModel: 'llama3.3',
    description: 'Local inference running on your own hardware.',
  },
  {
    id: 'ollama-cloud',
    name: 'Ollama Cloud',
    group: 'payg',
    groupLabel: GROUP_LABELS.payg,
    signupUrl: 'https://ollama.com/',
    baseUrl: 'https://ollama.com/v1',
    defaultModel: 'llama3.3',
    description: 'Hosted models on ollama.com via OpenAI-compatible API.',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://lmstudio.ai/',
    baseUrl: 'http://127.0.0.1:1234/v1',
    defaultModel: 'local-model',
    description: 'Cross-platform local LLM runner.',
  },
  {
    id: 'vllm',
    name: 'vLLM',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://vllm.ai/',
    baseUrl: 'http://127.0.0.1:8000/v1',
    defaultModel: 'hosted-model',
    description: 'High-throughput and memory-efficient local server.',
  },
  {
    id: 'atomic-chat',
    name: 'Atomic Chat',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://atomic.chat/',
    baseUrl: 'http://127.0.0.1:1337/v1',
    defaultModel: 'local-model',
    description: 'Local models through Atomic Chat’s OpenAI-compatible server.',
  },
  {
    id: 'llama-swap',
    name: 'Llama Swap',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://github.com/mostlygeek/llama-swap',
    baseUrl: 'http://127.0.0.1:8080/v1',
    defaultModel: 'default',
    description: 'Local proxy that hot-swaps llama.cpp backends on demand.',
  },
  {
    id: 'omlx',
    name: 'oMLX',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://github.com/ml-explore/mlx-examples',
    baseUrl: 'http://127.0.0.1:8080/v1',
    defaultModel: 'local-model',
    description: 'Run local models with oMLX (Apple Silicon friendly).',
  },
  {
    id: 'local-gguf',
    name: 'Local Inference (GGUF)',
    group: 'self-hosted',
    groupLabel: GROUP_LABELS['self-hosted'],
    signupUrl: 'https://github.com/ggerganov/llama.cpp',
    baseUrl: 'http://127.0.0.1:8080/v1',
    defaultModel: 'local-gguf',
    description: 'Local inference using quantized GGUF models (llama.cpp server).',
  },

  // WEB SEARCH / RESEARCH BYOK
  {
    id: 'exa',
    name: 'Exa AI',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://exa.ai/',
    baseUrl: 'https://api.exa.ai',
    defaultModel: 'exa-search',
    description: 'Neural / semantic search trained for AI agents and research discovery.',
    validation: 'key-only',
  },
  {
    id: 'tavily',
    name: 'Tavily',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://tavily.com/',
    baseUrl: 'https://api.tavily.com',
    defaultModel: 'tavily-search',
    description: 'AI search + extract for RAG agents with citations.',
    validation: 'key-only',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://brave.com/search/api/',
    baseUrl: 'https://api.search.brave.com',
    defaultModel: 'brave-search',
    description: 'Independent web index (not Google/Bing), low-latency agent search.',
    validation: 'key-only',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://www.firecrawl.dev/',
    baseUrl: 'https://api.firecrawl.dev/v1',
    defaultModel: 'firecrawl-search',
    description: 'Search + scrape + clean full-page content built for AI agents.',
    validation: 'key-only',
  },
  {
    id: 'serpapi',
    name: 'SerpAPI',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://serpapi.com/',
    baseUrl: 'https://serpapi.com',
    defaultModel: 'google',
    description: 'Multi-engine SERP API (Google, Bing, etc.) with deep results parsing.',
    validation: 'key-only',
  },
  {
    id: 'serper',
    name: 'Serper',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://serper.dev/',
    baseUrl: 'https://google.serper.dev',
    defaultModel: 'google-search',
    description: 'Cost-optimized Google Search API for agents.',
    validation: 'key-only',
  },
  {
    id: 'perplexity-sonar',
    name: 'Perplexity Sonar',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://www.perplexity.ai/settings/api',
    baseUrl: 'https://api.perplexity.ai',
    defaultModel: 'sonar-pro',
    description: 'Grounded web answers with citations (Sonar API).',
    validation: 'key-only',
  },
  {
    id: 'jina-search',
    name: 'Jina Search / Reader',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://jina.ai/',
    baseUrl: 'https://s.jina.ai',
    defaultModel: 'jina-search',
    description: 'Jina search + r.jina.ai reader for clean page extraction.',
    validation: 'key-only',
  },
  {
    id: 'you-search',
    name: 'You.com',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://you.com/',
    baseUrl: 'https://api.ydc-index.io',
    defaultModel: 'you-search',
    description: 'You.com web search with adjustable research depth.',
    validation: 'key-only',
  },
  {
    id: 'linkup',
    name: 'Linkup',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://www.linkup.so/',
    baseUrl: 'https://api.linkup.so/v1',
    defaultModel: 'linkup-search',
    description: 'Real-time multilingual web search API for AI agents.',
    validation: 'key-only',
  },
  {
    id: 'parallel-search',
    name: 'Parallel Search API',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://parallel.ai/',
    baseUrl: 'https://api.parallel.ai',
    defaultModel: 'parallel-search',
    description: 'Enterprise research search with evidence-backed outputs.',
    validation: 'key-only',
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://docs.searxng.org/',
    baseUrl: 'http://127.0.0.1:8080',
    defaultModel: 'searxng',
    description: 'Self-hosted metasearch. Set base URL to your SearXNG instance.',
    validation: 'key-only',
  },
  {
    id: 'kagi',
    name: 'Kagi Search',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://kagi.com/',
    baseUrl: 'https://kagi.com/api/v0',
    defaultModel: 'kagi-search',
    description: 'Ad-free premium search API for high-quality research.',
    validation: 'key-only',
  },
  {
    id: 'bocha',
    name: 'Bocha AI Search',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://open.bochaai.com/',
    baseUrl: 'https://api.bochaai.com/v1',
    defaultModel: 'bocha-web-search',
    description: 'Chinese / multilingual AI web search API for agents.',
    validation: 'key-only',
  },
  {
    id: 'scrapingdog',
    name: 'ScrapingDog',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://www.scrapingdog.com/',
    baseUrl: 'https://api.scrapingdog.com',
    defaultModel: 'google-search',
    description: 'SERP + scrape APIs (Google, Bing, etc.) for agent pipelines.',
    validation: 'key-only',
  },
  {
    id: 'valyu',
    name: 'Valyu',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://www.valyu.ai/',
    baseUrl: 'https://api.valyu.ai/v1',
    defaultModel: 'valyu-search',
    description: 'Deep research search API with structured evidence for agents.',
    validation: 'key-only',
  },
  {
    id: 'context7',
    name: 'Context7 Docs',
    group: 'web-search',
    groupLabel: GROUP_LABELS['web-search'],
    signupUrl: 'https://context7.com/',
    baseUrl: 'https://context7.com/api',
    defaultModel: 'docs-search',
    description: 'Up-to-date library/docs search for coding agents.',
    validation: 'key-only',
  },

  // IMAGE BYOK
  {
    id: 'openai-images',
    name: 'OpenAI Images',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://platform.openai.com/',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-image-1',
    description: 'GPT Image and DALL·E generation via your OpenAI key.',
    validation: 'key-only',
  },
  {
    id: 'black-forest-labs',
    name: 'Black Forest Labs (FLUX)',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://bfl.ai/',
    baseUrl: 'https://api.bfl.ai/v1',
    defaultModel: 'flux-pro-1.1',
    description: 'Official FLUX image models from Black Forest Labs.',
    validation: 'key-only',
  },
  {
    id: 'fal-ai',
    name: 'Fal.ai',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://fal.ai/',
    baseUrl: 'https://fal.run',
    defaultModel: 'fal-ai/flux/dev',
    description: 'Fast hosted diffusion, FLUX, and image models.',
    validation: 'key-only',
  },
  {
    id: 'replicate-images',
    name: 'Replicate (Images)',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://replicate.com/',
    baseUrl: 'https://api.replicate.com/v1',
    defaultModel: 'black-forest-labs/flux-schnell',
    description: 'Run open image and diffusion models with one API key.',
    validation: 'key-only',
  },
  {
    id: 'stability',
    name: 'Stability AI',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://platform.stability.ai/',
    baseUrl: 'https://api.stability.ai/v2beta',
    defaultModel: 'stable-image-ultra',
    description: 'Stable Diffusion / Stable Image models via Stability API.',
    validation: 'key-only',
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://ideogram.ai/',
    baseUrl: 'https://api.ideogram.ai',
    defaultModel: 'V_3',
    description: 'Ideogram image models with strong text-in-image rendering.',
    validation: 'key-only',
  },
  {
    id: 'recraft',
    name: 'Recraft',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://www.recraft.ai/',
    baseUrl: 'https://external.api.recraft.ai/v1',
    defaultModel: 'recraftv3',
    description: 'Recraft design-quality image generation and vector styles.',
    validation: 'key-only',
  },
  {
    id: 'together-images',
    name: 'Together AI (Images)',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://api.together.ai/',
    baseUrl: 'https://api.together.xyz/v1',
    defaultModel: 'black-forest-labs/FLUX.1-schnell',
    description: 'Image models (FLUX and others) via Together AI.',
    validation: 'key-only',
  },
  {
    id: 'fireworks-images',
    name: 'Fireworks (Images)',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://fireworks.ai/',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    defaultModel: 'accounts/fireworks/models/flux-1-dev-fp8',
    description: 'Hosted image models including FLUX on Fireworks.',
    validation: 'key-only',
  },
  {
    id: 'leonardo',
    name: 'Leonardo AI',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://leonardo.ai/',
    baseUrl: 'https://cloud.leonardo.ai/api/rest/v1',
    defaultModel: 'phoenix',
    description: 'Leonardo creative image generation API.',
    validation: 'key-only',
  },
  {
    id: 'midjourney-proxy',
    name: 'Midjourney (API proxy)',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://docs.midjourney.com/',
    baseUrl: 'https://YOUR_MJ_PROXY/v1',
    defaultModel: 'midjourney',
    description: 'Use an OpenAI-compatible Midjourney proxy. Set base URL to your gateway.',
    validation: 'key-only',
  },
  {
    id: 'google-imagen',
    name: 'Google Imagen',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/image/overview',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com',
    defaultModel: 'imagen-3.0-generate-002',
    description: 'Google Imagen via Vertex AI (API key / service account proxy).',
    validation: 'key-only',
  },
  {
    id: 'xai-images',
    name: 'xAI Grok Imagine',
    group: 'image-byok',
    groupLabel: GROUP_LABELS['image-byok'],
    signupUrl: 'https://console.x.ai/',
    baseUrl: 'https://api.x.ai/v1',
    defaultModel: 'grok-imagine',
    description: 'xAI image generation (Grok Imagine) via xAI API.',
    validation: 'key-only',
  },

  // VIDEO BYOK
  {
    id: 'runway',
    name: 'Runway',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://runwayml.com/',
    baseUrl: 'https://api.dev.runwayml.com/v1',
    defaultModel: 'gen4_turbo',
    description: 'Gen-4 and other Runway video models — mature production API.',
    validation: 'key-only',
  },
  {
    id: 'luma',
    name: 'Luma AI',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://lumalabs.ai/dream-machine',
    baseUrl: 'https://api.lumalabs.ai/dream-machine/v1',
    defaultModel: 'ray-2',
    description: 'Luma Dream Machine / Ray video generation API.',
    validation: 'key-only',
  },
  {
    id: 'kling',
    name: 'Kling AI',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://klingai.com/',
    baseUrl: 'https://api.klingai.com',
    defaultModel: 'kling-v2',
    description: 'Kling text-to-video and image-to-video API.',
    validation: 'key-only',
  },
  {
    id: 'pika',
    name: 'Pika',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://pika.art/',
    baseUrl: 'https://api.pika.art/v1',
    defaultModel: 'pika-2.2',
    description: 'Pika Labs video generation API.',
    validation: 'key-only',
  },
  {
    id: 'minimax-video',
    name: 'MiniMax Video',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://www.minimax.io/',
    baseUrl: 'https://api.minimax.io/v1',
    defaultModel: 'video-01',
    description: 'MiniMax Hailuo / video-01 generation models.',
    validation: 'key-only',
  },
  {
    id: 'replicate-video',
    name: 'Replicate (Video)',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://replicate.com/',
    baseUrl: 'https://api.replicate.com/v1',
    defaultModel: 'minimax/video-01',
    description: 'Video generation models hosted on Replicate.',
    validation: 'key-only',
  },
  {
    id: 'fal-video',
    name: 'Fal.ai (Video)',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://fal.ai/',
    baseUrl: 'https://fal.run',
    defaultModel: 'fal-ai/minimax-video',
    description: 'Hosted video models (MiniMax, Kling, etc.) on Fal.',
    validation: 'key-only',
  },
  {
    id: 'openai-sora',
    name: 'OpenAI Sora',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://platform.openai.com/',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'sora-2',
    description: 'OpenAI Sora video generation when available on your account.',
    validation: 'key-only',
  },
  {
    id: 'google-veo',
    name: 'Google Veo',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://cloud.google.com/vertex-ai/generative-ai/docs/video/overview',
    baseUrl: 'https://us-central1-aiplatform.googleapis.com',
    defaultModel: 'veo-2.0-generate-001',
    description: 'Google Veo video models via Vertex AI.',
    validation: 'key-only',
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://www.heygen.com/',
    baseUrl: 'https://api.heygen.com/v2',
    defaultModel: 'heygen-avatar',
    description: 'Avatar and talking-head video generation API.',
    validation: 'key-only',
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://www.synthesia.io/',
    baseUrl: 'https://api.synthesia.io/v2',
    defaultModel: 'synthesia-avatar',
    description: 'AI avatar video production API for explainers and training.',
    validation: 'key-only',
  },
  {
    id: 'haiper',
    name: 'Haiper',
    group: 'video-byok',
    groupLabel: GROUP_LABELS['video-byok'],
    signupUrl: 'https://haiper.ai/',
    baseUrl: 'https://api.haiper.ai/v1',
    defaultModel: 'haiper-video',
    description: 'Haiper text-to-video generation API.',
    validation: 'key-only',
  },

  // MCP SERVERS / TOOLS
  {
    id: 'parallel-mcp',
    name: 'Parallel Search MCP',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://parallel.ai/',
    baseUrl: 'https://api.parallel.ai',
    defaultModel: 'parallel-search-mcp',
    description: 'Parallel web-search MCP server for agent workflows.',
    validation: 'key-only',
  },
  {
    id: 'bright-data-mcp',
    name: 'Bright Data Web MCP',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://brightdata.com/',
    baseUrl: 'https://api.brightdata.com',
    defaultModel: 'bright-data-web-mcp',
    description: 'Bright Data web-scrape and search MCP integration.',
    validation: 'key-only',
  },
  {
    id: 'firecrawl-mcp',
    name: 'Firecrawl MCP',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://www.firecrawl.dev/',
    baseUrl: 'https://api.firecrawl.dev/v1',
    defaultModel: 'firecrawl-mcp',
    description: 'Firecrawl scrape/search MCP for agent extract workflows.',
    validation: 'key-only',
  },
  {
    id: 'exa-mcp',
    name: 'Exa MCP',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://exa.ai/',
    baseUrl: 'https://mcp.exa.ai',
    defaultModel: 'exa-mcp',
    description: 'Exa neural search as an MCP tool server.',
    validation: 'key-only',
  },
  {
    id: 'brave-mcp',
    name: 'Brave Search MCP',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://brave.com/search/api/',
    baseUrl: 'https://api.search.brave.com',
    defaultModel: 'brave-mcp',
    description: 'Brave Search exposed via MCP for agent tool-use.',
    validation: 'key-only',
  },
  {
    id: 'tavily-mcp',
    name: 'Tavily MCP',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://tavily.com/',
    baseUrl: 'https://api.tavily.com',
    defaultModel: 'tavily-mcp',
    description: 'Tavily search/extract MCP for RAG agents.',
    validation: 'key-only',
  },
  // App OAuth integrations (Gmail, Slack, GitHub, Notion, Linear, Zapier,
  // Browserbase, Composio, etc.) live under **Connectors** — not MCP tiles.
  {
    id: 'apify-mcp',
    name: 'Apify',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://apify.com/',
    baseUrl: 'https://api.apify.com/v2',
    defaultModel: 'apify-actors',
    description: 'Web scraping actors and datasets via Apify API / MCP.',
    validation: 'key-only',
  },
  {
    id: 'browser-use-mcp',
    name: 'Browser Use',
    group: 'mcp',
    groupLabel: GROUP_LABELS.mcp,
    signupUrl: 'https://browser-use.com/',
    baseUrl: 'https://api.browser-use.com/v1',
    defaultModel: 'browser-use',
    description: 'Agentic browser automation API for multi-step web tasks.',
    validation: 'key-only',
  },

  // AUDIO / TTS (key-only tiles for Library web-other)
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    group: 'services',
    groupLabel: GROUP_LABELS.services,
    signupUrl: 'https://elevenlabs.io/',
    baseUrl: 'https://api.elevenlabs.io/v1',
    defaultModel: 'eleven_multilingual_v2',
    description: 'High-quality TTS and voice cloning API.',
    validation: 'key-only',
  },
  {
    id: 'openai-audio',
    name: 'OpenAI Audio',
    group: 'services',
    groupLabel: GROUP_LABELS.services,
    signupUrl: 'https://platform.openai.com/',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini-tts',
    description: 'OpenAI TTS and Whisper speech-to-text.',
    validation: 'key-only',
  },
  {
    id: 'deepgram',
    name: 'Deepgram',
    group: 'services',
    groupLabel: GROUP_LABELS.services,
    signupUrl: 'https://deepgram.com/',
    baseUrl: 'https://api.deepgram.com/v1',
    defaultModel: 'nova-3',
    description: 'Speech-to-text and voice AI API.',
    validation: 'key-only',
  },
  {
    id: 'cartesia',
    name: 'Cartesia',
    group: 'services',
    groupLabel: GROUP_LABELS.services,
    signupUrl: 'https://cartesia.ai/',
    baseUrl: 'https://api.cartesia.ai',
    defaultModel: 'sonic-2',
    description: 'Low-latency realtime TTS for agents.',
    validation: 'key-only',
  },
];

export function getProviderById(id: string): ProviderCatalogEntry | undefined {
  return PROVIDER_CATALOG.find((entry) => entry.id === id);
}

export function getRecommendedProviders(): ProviderCatalogEntry[] {
  return PROVIDER_CATALOG.filter((entry) => entry.recommended);
}

export function filterProvidersBySection(
  section: 'ai' | 'web-other',
  providers: ProviderCatalogEntry[] = PROVIDER_CATALOG,
): ProviderCatalogEntry[] {
  const allowed = section === 'ai' ? AI_PROVIDER_GROUPS : WEB_OTHER_PROVIDER_GROUPS;
  return providers.filter((provider) => allowed.includes(provider.group));
}

export function isAiProviderGroup(group: ProviderGroup): boolean {
  return AI_PROVIDER_GROUPS.includes(group);
}

export function groupProvidersByLabel(
  providers: ProviderCatalogEntry[] = PROVIDER_CATALOG,
): Array<{ label: string; providers: ProviderCatalogEntry[] }> {
  const groups = new Map<string, ProviderCatalogEntry[]>();
  for (const provider of providers) {
    const bucket = groups.get(provider.groupLabel) ?? [];
    bucket.push(provider);
    groups.set(provider.groupLabel, bucket);
  }
  return [...groups.entries()].map(([label, entries]) => ({
    label,
    providers: entries,
  }));
}