//! P44.3 — VENDORED models.dev provider directory (auto-generated seed).
//!
//! The authoritative provider set OpenCode/Hermes consume: 212 providers
//! from models.dev (id · name · api-key env · base URL · auth shape ·
//! transport family). Generated from `models.dev/api.json`; refreshed by
//! the P14.5 catalog sync. NEVER contains a key — only the env-var NAME.
//! Edit the generator, not this file.

use crate::provider::{Auth, Transport};

/// One vendored provider row: `(id, name, api_key_env, base_url, auth, transport)`.
pub struct SeedRow {
    pub id: &'static str,
    pub name: &'static str,
    pub env: &'static [&'static str],
    pub base_url: &'static str,
    pub auth: Auth,
    pub transport: Transport,
}

pub const PROVIDER_SEED: &[SeedRow] = &[
    SeedRow {
        id: "302ai",
        name: "302.AI",
        env: &["302AI_API_KEY"],
        base_url: "https://api.302.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "abacus",
        name: "Abacus",
        env: &["ABACUS_API_KEY"],
        base_url: "https://routellm.abacus.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "abliteration-ai",
        name: "abliteration.ai",
        env: &["ABLIT_KEY"],
        base_url: "https://api.abliteration.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "above",
        name: "above.dev",
        env: &["ABOVE_API_KEY"],
        base_url: "https://api.above.dev/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "agentrouter",
        name: "AgentRouter",
        env: &["AGENTROUTER_API_KEY"],
        base_url: "https://agentrouter.org/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "agnes",
        name: "Agnes AI",
        env: &["AGNES_API_KEY"],
        base_url: "https://apihub.agnes-ai.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "ai-router",
        name: "AI-ROUTER",
        env: &["AI_ROUTER_API_KEY"],
        base_url: "https://api.ai-router.dev/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "aiand",
        name: "ai&",
        env: &["AIAND_API_KEY"],
        base_url: "https://api.aiand.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "aihubmix",
        name: "AIHubMix",
        env: &["AIHUBMIX_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "aixy",
        name: "Aixy",
        env: &["AIXY_API_KEY"],
        base_url: "https://api.aixy-gateway.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "aki-io",
        name: "AKI.IO",
        env: &["AKI_IO_API_KEY"],
        base_url: "https://aki.io/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "alibaba",
        name: "Alibaba",
        env: &["DASHSCOPE_API_KEY"],
        base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "alibaba-cn",
        name: "Alibaba (China)",
        env: &["DASHSCOPE_API_KEY"],
        base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "alibaba-coding-plan",
        name: "Alibaba Coding Plan",
        env: &["ALIBABA_CODING_PLAN_API_KEY"],
        base_url: "https://coding-intl.dashscope.aliyuncs.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "alibaba-coding-plan-cn",
        name: "Alibaba Coding Plan (China)",
        env: &["ALIBABA_CODING_PLAN_API_KEY"],
        base_url: "https://coding.dashscope.aliyuncs.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "alibaba-token-plan",
        name: "Alibaba Token Plan",
        env: &["ALIBABA_TOKEN_PLAN_API_KEY"],
        base_url: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "alibaba-token-plan-cn",
        name: "Alibaba Token Plan (China)",
        env: &["ALIBABA_TOKEN_PLAN_API_KEY"],
        base_url: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "amazon-bedrock",
        name: "Amazon Bedrock",
        env: &[
            "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_REGION",
            "AWS_BEARER_TOKEN_BEDROCK",
        ],
        base_url: "",
        auth: Auth::AwsSdk,
        transport: Transport::BedrockConverse,
    },
    SeedRow {
        id: "ambient",
        name: "Ambient",
        env: &["AMBIENT_API_KEY"],
        base_url: "https://api.ambient.xyz/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "amd",
        name: "AMD",
        env: &["AMD_API_KEY"],
        base_url: "https://developer.amd.com.cn/radeon/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "anthropic",
        name: "Anthropic",
        env: &["ANTHROPIC_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "anyapi",
        name: "AnyAPI",
        env: &["ANYAPI_API_KEY"],
        base_url: "https://api.anyapi.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "arcee",
        name: "Arcee",
        env: &["ARCEE_API_KEY"],
        base_url: "https://api.arcee.ai/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "atomic-chat",
        name: "Atomic Chat",
        env: &["ATOMIC_CHAT_API_KEY"],
        base_url: "http://127.0.0.1:1337/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "auriko",
        name: "Auriko",
        env: &["AURIKO_API_KEY"],
        base_url: "https://api.auriko.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "azure",
        name: "Azure",
        env: &["AZURE_RESOURCE_NAME", "AZURE_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "azure-cognitive-services",
        name: "Azure Cognitive Services",
        env: &[
            "AZURE_COGNITIVE_SERVICES_RESOURCE_NAME",
            "AZURE_COGNITIVE_SERVICES_API_KEY",
        ],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "bailing",
        name: "Bailing",
        env: &["BAILING_API_TOKEN"],
        base_url: "https://api.tbox.cn/api/llm/v1/chat/completions",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "baseten",
        name: "Baseten",
        env: &["BASETEN_API_KEY"],
        base_url: "https://inference.baseten.co/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "berget",
        name: "Berget.AI",
        env: &["BERGET_API_KEY"],
        base_url: "https://api.berget.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "blueclaw",
        name: "Blue Claw",
        env: &["BLUECLAW_API_KEY"],
        base_url: "https://openai.blueclaw.network/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "bothub",
        name: "Bothub",
        env: &["BOTHUB_API_KEY"],
        base_url: "https://openai.bothub.ru/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cerebras",
        name: "Cerebras",
        env: &["CEREBRAS_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "chutes",
        name: "Chutes",
        env: &["CHUTES_API_KEY"],
        base_url: "https://llm.chutes.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "clarifai",
        name: "Clarifai",
        env: &["CLARIFAI_PAT"],
        base_url: "https://api.clarifai.com/v2/ext/openai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "claudinio",
        name: "Claudinio",
        env: &["CLAUDINIO_API_KEY"],
        base_url: "https://api.claudin.io/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cline-pass",
        name: "ClinePass",
        env: &["CLINE_API_KEY"],
        base_url: "https://api.cline.bot/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cloudferro-sherlock",
        name: "CloudFerro Sherlock",
        env: &["CLOUDFERRO_SHERLOCK_API_KEY"],
        base_url: "https://api-sherlock.cloudferro.com/openai/v1/",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cloudflare-ai-gateway",
        name: "Cloudflare AI Gateway",
        env: &[
            "CLOUDFLARE_API_TOKEN",
            "CLOUDFLARE_ACCOUNT_ID",
            "CLOUDFLARE_GATEWAY_ID",
        ],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cloudflare-workers-ai",
        name: "Cloudflare Workers AI",
        env: &["CLOUDFLARE_ACCOUNT_ID", "CLOUDFLARE_API_KEY"],
        base_url: "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cohere",
        name: "Cohere",
        env: &["COHERE_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "coralbricks",
        name: "CoralBricks",
        env: &["CORAL_API_KEY"],
        base_url: "https://inference.coralbricks.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "cortecs",
        name: "Cortecs",
        env: &["CORTECS_API_KEY"],
        base_url: "https://api.cortecs.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "crof",
        name: "CrofAI",
        env: &["CROF_API_KEY"],
        base_url: "https://crof.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "crossmodel",
        name: "CrossModel",
        env: &["CROSSMODEL_API_KEY"],
        base_url: "https://api.crossmodel.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "crusoe",
        name: "Crusoe",
        env: &["CRUSOE_API_KEY"],
        base_url: "https://api.inference.crusoecloud.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "daoxe",
        name: "DaoXE",
        env: &["DAOXE_API_KEY"],
        base_url: "https://daoxe.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "databricks",
        name: "Databricks",
        env: &["DATABRICKS_HOST", "DATABRICKS_TOKEN"],
        base_url: "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "deepinfra",
        name: "Deep Infra",
        env: &["DEEPINFRA_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "deepseek",
        name: "DeepSeek",
        env: &["DEEPSEEK_API_KEY"],
        base_url: "https://api.deepseek.com",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "digitalocean",
        name: "DigitalOcean",
        env: &["DIGITALOCEAN_ACCESS_TOKEN"],
        base_url: "https://inference.do-ai.run/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "dinference",
        name: "DInference",
        env: &["DINFERENCE_API_KEY"],
        base_url: "https://api.dinference.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "drun",
        name: "D.Run (China)",
        env: &["DRUN_API_KEY"],
        base_url: "https://chat.d.run/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "ebcloud",
        name: "EBCloud",
        env: &["EBCLOUD_API_KEY"],
        base_url: "https://maas-api.ebcloud.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "echo",
        name: "Echo",
        env: &["ECHO_API_KEY"],
        base_url: "https://echo.tracerml.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "edenai",
        name: "Eden AI",
        env: &["EDENAI_API_KEY"],
        base_url: "https://api.edenai.run/v3",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "empiriolabs",
        name: "EmpirioLabs AI",
        env: &["EMPIRIOLABS_API_KEY"],
        base_url: "https://api.empiriolabs.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "evroc",
        name: "evroc",
        env: &["EVROC_API_KEY"],
        base_url: "https://models.think.evroc.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "fastrouter",
        name: "FastRouter",
        env: &["FASTROUTER_API_KEY"],
        base_url: "https://go.fastrouter.ai/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "fireworks-ai",
        name: "Fireworks AI",
        env: &["FIREWORKS_API_KEY"],
        base_url: "https://api.fireworks.ai/inference/v1/",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "freemodel",
        name: "FreeModel",
        env: &["FREEMODEL_API_KEY"],
        base_url: "https://cc.freemodel.dev/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "friendli",
        name: "Friendli",
        env: &["FRIENDLI_TOKEN"],
        base_url: "https://api.friendli.ai/serverless/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "frogbot",
        name: "FrogBot",
        env: &["FROGBOT_API_KEY"],
        base_url: "https://app.frogbot.ai/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "github-copilot",
        name: "GitHub Copilot",
        env: &["GITHUB_TOKEN"],
        base_url: "https://api.githubcopilot.com",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "gitlab",
        name: "GitLab Duo",
        env: &["GITLAB_TOKEN"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "gmicloud",
        name: "GMI Cloud",
        env: &["GMICLOUD_API_KEY"],
        base_url: "https://api.gmi-serving.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "google",
        name: "Google",
        env: &[
            "GOOGLE_API_KEY",
            "GOOGLE_GENERATIVE_AI_API_KEY",
            "GEMINI_API_KEY",
        ],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "google-vertex",
        name: "Vertex",
        env: &[
            "GOOGLE_VERTEX_PROJECT",
            "GOOGLE_VERTEX_LOCATION",
            "GOOGLE_APPLICATION_CREDENTIALS",
        ],
        base_url: "",
        auth: Auth::Vertex,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "google-vertex-anthropic",
        name: "Vertex (Anthropic)",
        env: &[
            "GOOGLE_VERTEX_PROJECT",
            "GOOGLE_VERTEX_LOCATION",
            "GOOGLE_APPLICATION_CREDENTIALS",
        ],
        base_url: "",
        auth: Auth::Vertex,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "greenpt",
        name: "GreenPT",
        env: &["GREENPT_API_KEY"],
        base_url: "https://api.greenpt.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "groq",
        name: "Groq",
        env: &["GROQ_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "helicone",
        name: "Helicone",
        env: &["HELICONE_API_KEY"],
        base_url: "https://ai-gateway.helicone.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "hetzner",
        name: "Hetzner",
        env: &["HETZNER_API_KEY"],
        base_url: "https://inference.hetzner.com/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "hpc-ai",
        name: "HPC-AI",
        env: &["HPC_AI_API_KEY"],
        base_url: "https://api.hpc-ai.com/inference/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "huggingface",
        name: "Hugging Face",
        env: &["HF_TOKEN"],
        base_url: "https://router.huggingface.co/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "hyper",
        name: "Charm Hyper",
        env: &["HYPER_API_KEY"],
        base_url: "https://hyper.charm.land/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "iflowcn",
        name: "iFlow",
        env: &["IFLOW_API_KEY"],
        base_url: "https://apis.iflow.cn/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "impossibl",
        name: "Impossibl",
        env: &["IMPOSSIBL_API_KEY"],
        base_url: "https://api.impossibl.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "inception",
        name: "Inception",
        env: &["INCEPTION_API_KEY"],
        base_url: "https://api.inceptionlabs.ai/v1/",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "inceptron",
        name: "Inceptron",
        env: &["INCEPTRON_API_KEY"],
        base_url: "https://api.inceptron.io/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "inference",
        name: "Inference",
        env: &["INFERENCE_API_KEY"],
        base_url: "https://inference.net/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "inferx",
        name: "InferX",
        env: &["INFERX_API_KEY"],
        base_url: "https://model.inferx.net/endpoints/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "infomaniak",
        name: "Infomaniak",
        env: &["INFOMANIAK_API_KEY", "INFOMANIAK_PRODUCT_ID"],
        base_url: "https://api.infomaniak.com/2/ai/${INFOMANIAK_PRODUCT_ID}/openai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "io-net",
        name: "IO.NET",
        env: &["IOINTELLIGENCE_API_KEY"],
        base_url: "https://api.intelligence.io.solutions/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "iteracompute",
        name: "IteraCompute",
        env: &["ITERACOMPUTE_API_KEY"],
        base_url: "https://api.iteracompute.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "jalapeno",
        name: "Jalapeno Cloud",
        env: &["JALAPENO_API_KEY"],
        base_url: "https://api.jalapeno-cloud.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "jiekou",
        name: "Jiekou.AI",
        env: &["JIEKOU_API_KEY"],
        base_url: "https://api.jiekou.ai/openai",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "kenari",
        name: "Kenari",
        env: &["KENARI_API_KEY"],
        base_url: "https://kenari.id/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "kilo",
        name: "Kilo Gateway",
        env: &["KILO_API_KEY"],
        base_url: "https://api.kilo.ai/api/gateway",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "kimi-for-coding",
        name: "Kimi For Coding",
        env: &["KIMI_API_KEY"],
        base_url: "https://api.kimi.com/coding/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "klokintegration",
        name: "klokintegration.se",
        env: &["KLOKINTEGRATION_API_KEY"],
        base_url: "https://api-gw.klok.ipaas.se/proxy/kloker-key/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "kosmik",
        name: "Kosmik Compute",
        env: &["KOSMIK_API_KEY"],
        base_url: "https://api.koscompute.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "kuae-cloud-coding-plan",
        name: "KUAE Cloud Coding Plan",
        env: &["KUAE_API_KEY"],
        base_url: "https://coding-plan-endpoint.kuaecloud.net/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "lilac",
        name: "Lilac",
        env: &["LILAC_API_KEY"],
        base_url: "https://api.getlilac.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "llama",
        name: "Llama",
        env: &["LLAMA_API_KEY"],
        base_url: "https://api.llama.com/compat/v1/",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "llmgateway",
        name: "DevPass (LLM Gateway)",
        env: &["LLMGATEWAY_API_KEY"],
        base_url: "https://api.llmgateway.io/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "llmgateway-providers",
        name: "LLM Gateway",
        env: &["LLMGATEWAY_API_KEY"],
        base_url: "https://api.llmgateway.io/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "llmtech",
        name: "LLM Tech",
        env: &["LLMTECH_API_KEY"],
        base_url: "https://api.llmtech.eu/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "llmtr",
        name: "LLMTR",
        env: &["LLMTR_API_KEY"],
        base_url: "https://llmtr.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "lmstudio",
        name: "LMStudio",
        env: &["LMSTUDIO_API_KEY"],
        base_url: "http://127.0.0.1:1234/v1",
        auth: Auth::Keyless,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "longcat",
        name: "LongCat",
        env: &["LONGCAT_API_KEY"],
        base_url: "https://api.longcat.chat/openai",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "lucidquery",
        name: "LucidQuery",
        env: &["LUCIDQUERY_API_KEY"],
        base_url: "https://api.lucidquery.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "lynkr",
        name: "Lynkr",
        env: &["LYNKR_API_KEY"],
        base_url: "http://127.0.0.1:8081/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "meganova",
        name: "Meganova",
        env: &["MEGANOVA_API_KEY"],
        base_url: "https://api.meganova.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "merge-gateway",
        name: "Merge Gateway",
        env: &["MERGE_GATEWAY_API_KEY"],
        base_url: "https://api-gateway.merge.dev/v1/ai-sdk",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "meta",
        name: "Meta",
        env: &["META_MODEL_API_KEY"],
        base_url: "https://api.meta.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "minimax",
        name: "MiniMax (minimax.io)",
        env: &["MINIMAX_API_KEY"],
        base_url: "https://api.minimax.io/anthropic/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "minimax-cn",
        name: "MiniMax (minimaxi.com)",
        env: &["MINIMAX_API_KEY"],
        base_url: "https://api.minimaxi.com/anthropic/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "minimax-cn-coding-plan",
        name: "MiniMax Token Plan (minimaxi.com)",
        env: &["MINIMAX_API_KEY"],
        base_url: "https://api.minimaxi.com/anthropic/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "minimax-coding-plan",
        name: "MiniMax Token Plan (minimax.io)",
        env: &["MINIMAX_API_KEY"],
        base_url: "https://api.minimax.io/anthropic/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "mistral",
        name: "Mistral",
        env: &["MISTRAL_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "mixlayer",
        name: "Mixlayer",
        env: &["MIXLAYER_API_KEY"],
        base_url: "https://models.mixlayer.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "moark",
        name: "Moark",
        env: &["MOARK_API_KEY"],
        base_url: "https://moark.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "modal",
        name: "Modal",
        env: &["MODAL_PROXY_TOKEN"],
        base_url: "https://inference.us-west.modal.direct/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "model-oracle-ai",
        name: "Model Oracle AI",
        env: &["MODEL_ORACLE_API_KEY"],
        base_url: "https://api.modeloracle.com/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "modelis",
        name: "Modelis",
        env: &["MODELIS_API_KEY"],
        base_url: "https://modelishub.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "modelscope",
        name: "ModelScope",
        env: &["MODELSCOPE_API_KEY"],
        base_url: "https://api-inference.modelscope.cn/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "moonshotai",
        name: "Moonshot AI",
        env: &["MOONSHOT_API_KEY"],
        base_url: "https://api.moonshot.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "moonshotai-cn",
        name: "Moonshot AI (China)",
        env: &["MOONSHOT_API_KEY"],
        base_url: "https://api.moonshot.cn/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "morph",
        name: "Morph",
        env: &["MORPH_API_KEY"],
        base_url: "https://api.morphllm.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "nano-gpt",
        name: "NanoGPT",
        env: &["NANO_GPT_API_KEY"],
        base_url: "https://nano-gpt.com/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "nearai",
        name: "NEAR AI Cloud",
        env: &["NEARAI_API_KEY"],
        base_url: "https://cloud-api.near.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "nebius",
        name: "Nebius Token Factory",
        env: &["NEBIUS_API_KEY"],
        base_url: "https://api.tokenfactory.nebius.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "neon",
        name: "Neon",
        env: &["NEON_AI_GATEWAY_BASE_URL", "NEON_AI_GATEWAY_TOKEN"],
        base_url: "${NEON_AI_GATEWAY_BASE_URL}/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "neosmith",
        name: "NeoSmith",
        env: &["NEOSMITH_API_KEY"],
        base_url: "https://router.neosmith.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "neuralwatt",
        name: "Neuralwatt",
        env: &["NEURALWATT_API_KEY"],
        base_url: "https://api.neuralwatt.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "nova",
        name: "Nova",
        env: &["NOVA_API_KEY"],
        base_url: "https://api.nova.amazon.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "novita-ai",
        name: "NovitaAI",
        env: &["NOVITA_API_KEY"],
        base_url: "https://api.novita.ai/openai",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "nvidia",
        name: "Nvidia",
        env: &["NVIDIA_API_KEY"],
        base_url: "https://integrate.api.nvidia.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "ofox",
        name: "Ofox",
        env: &["OFOX_API_KEY"],
        base_url: "https://api.ofox.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "ollama-cloud",
        name: "Ollama Cloud",
        env: &["OLLAMA_API_KEY"],
        base_url: "https://ollama.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "openai",
        name: "OpenAI",
        env: &["OPENAI_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "opencode",
        name: "OpenCode Zen",
        env: &["OPENCODE_API_KEY"],
        base_url: "https://opencode.ai/zen/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "opencode-go",
        name: "OpenCode Go",
        env: &["OPENCODE_API_KEY"],
        base_url: "https://opencode.ai/zen/go/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "openreason",
        name: "OpenReason",
        env: &["OPENREASON_API_KEY"],
        base_url: "https://api.openreason.app/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "openrouter",
        name: "OpenRouter",
        env: &["OPENROUTER_API_KEY"],
        base_url: "https://openrouter.ai/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "opper",
        name: "Opper",
        env: &["OPPER_API_KEY"],
        base_url: "https://api.opper.ai/v3/compat",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "orcarouter",
        name: "OrcaRouter",
        env: &["ORCAROUTER_API_KEY"],
        base_url: "https://api.orcarouter.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "ovhcloud",
        name: "OVHcloud AI Endpoints",
        env: &["OVHCLOUD_API_KEY"],
        base_url: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "pendra",
        name: "Pendra",
        env: &["PENDRA_API_KEY"],
        base_url: "https://api.pendra.ai/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "perplexity",
        name: "Perplexity",
        env: &["PERPLEXITY_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "perplexity-agent",
        name: "Perplexity Agent",
        env: &["PERPLEXITY_API_KEY"],
        base_url: "https://api.perplexity.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "pioneer",
        name: "Pioneer",
        env: &["PIONEER_API_KEY"],
        base_url: "https://api.pioneer.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "poe",
        name: "Poe",
        env: &["POE_API_KEY"],
        base_url: "https://api.poe.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "poolside",
        name: "Poolside",
        env: &["POOLSIDE_API_KEY"],
        base_url: "https://inference.poolside.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "privatemode-ai",
        name: "Privatemode AI",
        env: &["PRIVATEMODE_API_KEY", "PRIVATEMODE_ENDPOINT"],
        base_url: "http://localhost:8080/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "qihang-ai",
        name: "QiHang",
        env: &["QIHANG_API_KEY"],
        base_url: "https://api.qhaigc.net/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "qiniu-ai",
        name: "Qiniu",
        env: &["QINIU_API_KEY"],
        base_url: "https://api.qnaigc.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "qvac",
        name: "QVAC",
        env: &["QVAC_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "regolo-ai",
        name: "Regolo AI",
        env: &["REGOLO_API_KEY"],
        base_url: "https://api.regolo.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "requesty",
        name: "Requesty",
        env: &["REQUESTY_API_KEY"],
        base_url: "https://router.requesty.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "routing-run",
        name: "routing.run",
        env: &["ROUTING_RUN_API_KEY"],
        base_url: "https://api.routing.run/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "runinfra",
        name: "RunInfra",
        env: &["RUNINFRA_GATEWAY_KEY"],
        base_url: "https://api.runinfra.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "sakana",
        name: "Sakana AI",
        env: &["SAKANA_API_KEY"],
        base_url: "https://api.sakana.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "salad-cloud",
        name: "SaladCloud AI Gateway",
        env: &["SALAD_CLOUD_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "sap-ai-core",
        name: "SAP AI Core",
        env: &["AICORE_SERVICE_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "sarvam",
        name: "Sarvam AI",
        env: &["SARVAM_API_KEY"],
        base_url: "https://api.sarvam.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "scaleway",
        name: "Scaleway",
        env: &["SCALEWAY_API_KEY"],
        base_url: "https://api.scaleway.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "scnet-token-plan",
        name: "SCNet Token Plan",
        env: &["SCNET_API_KEY"],
        base_url: "https://api.scnet.cn/api/llm/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "scx-ai",
        name: "SCX.ai",
        env: &["SCX_API_KEY"],
        base_url: "https://api.scx.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "sensenova",
        name: "SenseNova (China)",
        env: &["SENSENOVA_API_KEY"],
        base_url: "https://token.sensenova.cn/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "siliconflow",
        name: "SiliconFlow",
        env: &["SILICONFLOW_API_KEY"],
        base_url: "https://api.siliconflow.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "siliconflow-cn",
        name: "SiliconFlow (China)",
        env: &["SILICONFLOW_CN_API_KEY"],
        base_url: "https://api.siliconflow.cn/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "snowflake-cortex",
        name: "Snowflake Cortex",
        env: &["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_CORTEX_PAT"],
        base_url: "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "stackit",
        name: "STACKIT",
        env: &["STACKIT_API_KEY"],
        base_url: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "standardcompute",
        name: "Standard Compute",
        env: &["STANDARDCOMPUTE_API_KEY"],
        base_url: "https://api.stdcmpt.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "stepfun",
        name: "StepFun (China)",
        env: &["STEPFUN_API_KEY"],
        base_url: "https://api.stepfun.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "stepfun-ai",
        name: "StepFun (Global)",
        env: &["STEPFUN_API_KEY"],
        base_url: "https://api.stepfun.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "stepfun-ai-step-plan",
        name: "StepFun Step Plan (Global)",
        env: &["STEPFUN_API_KEY"],
        base_url: "https://api.stepfun.ai/step_plan/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "stepfun-step-plan",
        name: "StepFun Step Plan (China)",
        env: &["STEPFUN_API_KEY"],
        base_url: "https://api.stepfun.com/step_plan/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "subconscious",
        name: "Subconscious",
        env: &["SUBCONSCIOUS_API_KEY"],
        base_url: "https://api.subconscious.dev/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "submodel",
        name: "submodel",
        env: &["SUBMODEL_INSTAGEN_ACCESS_KEY"],
        base_url: "https://llm.submodel.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "synthetic",
        name: "Synthetic",
        env: &["SYNTHETIC_API_KEY"],
        base_url: "https://api.synthetic.new/openai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "tencent-coding-plan",
        name: "Tencent Coding Plan (China)",
        env: &["TENCENT_CODING_PLAN_API_KEY"],
        base_url: "https://api.lkeap.cloud.tencent.com/coding/v3",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "tencent-token-plan",
        name: "Tencent Token Plan",
        env: &["TENCENT_TOKEN_PLAN_API_KEY"],
        base_url: "https://api.lkeap.cloud.tencent.com/plan/v3",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "tencent-tokenhub",
        name: "Tencent TokenHub",
        env: &["TENCENT_TOKENHUB_API_KEY"],
        base_url: "https://tokenhub.tencentmaas.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "tensorx",
        name: "TensorX",
        env: &["TENSORX_API_KEY"],
        base_url: "https://api.tensorx.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "the-grid-ai",
        name: "The Grid AI",
        env: &["THEGRID_API_KEY"],
        base_url: "https://api.thegrid.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "thinkingmachines",
        name: "Thinking Machines",
        env: &["TINKER_API_KEY"],
        base_url: "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::AnthropicMessages,
    },
    SeedRow {
        id: "tinfoil",
        name: "Tinfoil",
        env: &["TINFOIL_API_KEY"],
        base_url: "https://inference.tinfoil.sh/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "togetherai",
        name: "Together AI",
        env: &["TOGETHER_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "tokengo",
        name: "TokenGo",
        env: &["TOKENGO_API_KEY"],
        base_url: "https://api.tokengo.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "tokenrouter",
        name: "TokenRouter",
        env: &["TOKENROUTER_API_KEY"],
        base_url: "https://api.tokenrouter.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "trustedrouter",
        name: "TrustedRouter",
        env: &["TRUSTEDROUTER_API_KEY"],
        base_url: "https://api.trustedrouter.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "umans-ai",
        name: "Umans AI",
        env: &["UMANS_AI_API_KEY"],
        base_url: "https://api.code.umans.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "umans-ai-coding-plan",
        name: "Umans AI Coding Plan",
        env: &["UMANS_AI_CODING_PLAN_API_KEY"],
        base_url: "https://api.code.umans.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "unorouter",
        name: "UnoRouter",
        env: &["UNOROUTER_API_KEY"],
        base_url: "https://api.unorouter.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "upstage",
        name: "Upstage",
        env: &["UPSTAGE_API_KEY"],
        base_url: "https://api.upstage.ai/v1/solar",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "v0",
        name: "v0",
        env: &["V0_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "vancine",
        name: "Vancine",
        env: &["VANCINE_API_KEY"],
        base_url: "https://vancine.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "venice",
        name: "Venice AI",
        env: &["VENICE_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "vercel",
        name: "Vercel AI Gateway",
        env: &["AI_GATEWAY_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "vivgrid",
        name: "Vivgrid",
        env: &["VIVGRID_API_KEY"],
        base_url: "https://api.vivgrid.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "volcengine",
        name: "Volcengine Ark",
        env: &["ARK_API_KEY"],
        base_url: "https://ark.cn-beijing.volces.com/api/v3",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "volcengine-coding-plan",
        name: "Volcengine Ark Coding Plan",
        env: &["ARK_CODING_PLAN_API_KEY"],
        base_url: "https://ark.cn-beijing.volces.com/api/coding/v3",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "vultr",
        name: "Vultr",
        env: &["VULTR_API_KEY"],
        base_url: "https://api.vultrinference.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "wafer.ai",
        name: "Wafer",
        env: &["WAFER_API_KEY"],
        base_url: "https://pass.wafer.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "wandb",
        name: "Weights & Biases",
        env: &["WANDB_API_KEY"],
        base_url: "https://api.inference.wandb.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "watsonx",
        name: "watsonx.ai",
        env: &["WATSONX_AI_APIKEY", "WATSONX_AI_PROJECT_ID"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "xai",
        name: "xAI",
        env: &["XAI_API_KEY"],
        base_url: "",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "xiaomi",
        name: "Xiaomi",
        env: &["XIAOMI_API_KEY"],
        base_url: "https://api.xiaomimimo.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "xiaomi-token-plan-ams",
        name: "Xiaomi Token Plan (Europe)",
        env: &["XIAOMI_API_KEY"],
        base_url: "https://token-plan-ams.xiaomimimo.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "xiaomi-token-plan-cn",
        name: "Xiaomi Token Plan (China)",
        env: &["XIAOMI_API_KEY"],
        base_url: "https://token-plan-cn.xiaomimimo.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "xiaomi-token-plan-sgp",
        name: "Xiaomi Token Plan (Singapore)",
        env: &["XIAOMI_API_KEY"],
        base_url: "https://token-plan-sgp.xiaomimimo.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "xpersona",
        name: "Xpersona",
        env: &["XPERSONA_API_KEY"],
        base_url: "https://www.xpersona.co/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zai",
        name: "Z.AI",
        env: &["ZHIPU_API_KEY"],
        base_url: "https://api.z.ai/api/paas/v4",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zai-coding-plan",
        name: "Z.AI Coding Plan",
        env: &["ZHIPU_API_KEY"],
        base_url: "https://api.z.ai/api/coding/paas/v4",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zeldoc",
        name: "Zeldoc",
        env: &["ZELDOC_API_KEY"],
        base_url: "https://api.zeldoc.ai/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zenifra",
        name: "Zenifra",
        env: &["ZENIFRA_AI_KEY"],
        base_url: "https://ai.zenifra.com/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zenmux",
        name: "ZenMux",
        env: &["ZENMUX_API_KEY"],
        base_url: "https://zenmux.ai/api/v1",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zhipuai",
        name: "Zhipu AI",
        env: &["ZHIPU_API_KEY"],
        base_url: "https://open.bigmodel.cn/api/paas/v4",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
    SeedRow {
        id: "zhipuai-coding-plan",
        name: "Zhipu AI Coding Plan",
        env: &["ZHIPU_API_KEY"],
        base_url: "https://open.bigmodel.cn/api/coding/paas/v4",
        auth: Auth::ApiKeyEnv,
        transport: Transport::OpenaiChat,
    },
];
